### ISSUE TITLE
Not working Gitlab CI + yarn

### ISSUE THREAD

**Issue by ties-s** [alexindigo/install-peers#5] opened 2021-05-10 12:27 UTC
Works fine locally, but not on CI. Packages don't get installed.

**Comment by ayan4m1** [comment] 2021-08-29 02:16
Can you provide a log (with any secrets redacted) and indicate what commands you are running in the CI environment?

**Comment by ayan4m1** [comment] 2022-05-22 20:44
Looks like #6 is a duplicate of this, both should be resolved with install-peers 1.0.4. Please retest.

**Closed as completed** 2022-05-25 10:39 UTC
